name: CI/CD for Chatbot OCR

on:
  push:
    branches:
      main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      -
        name: Docker Buildx
        uses: docker/setup-buildx-action@v3

      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: True
          tags: ${{ vars.DOCKERHUB_USERNAME }}/chatbot-ocr:0.1